import type { Metadata } from "next";
import Script from "next/script";
import { Geist, Geist_Mono } from "next/font/google";
import Layout from "./components/layout/layout";
import { RoleProvider } from "./context/roleContextProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ZIPPLE",
  description: "Generated by create next app",
  icons: {
    icon: "/logo_icon.svg",
    shortcut: "/logo_icon.svg", // Safari용
    apple: "/logo_icon.svg", // iOS 앱용
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Script
          strategy="beforeInteractive"
          src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"
        />
        <RoleProvider>
          <Layout>{children}</Layout>
        </RoleProvider>
      </body>
    </html>
  );
}
